name: CI Gitops

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            derivedpuma7/gitops:${{github.sha}}
            derivedpuma7/gitops:latest

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "5.6.0"

      - name: Update Kubernetes Resources
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd k8s
          kustomize edit set image goserver=$DOCKER_USERNAME/gitops:$GITHUB_SHA

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git commit -am "ci: Update docker image version"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: derivedpuma7/go-gitops